site_name: QBT-Lite Documentation
site_description: A lightweight quantitative backtesting framework in Python
site_author: Haozheng Li
repo_url: https://github.com/LinShuyue2003/qbt-lite
repo_name: qbt-lite

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Architecture: architecture.md
  - Strategies: strategies.md
  - Data Sources: data.md
  - Reporting & Metrics: reporting.md
  - CLI Reference: cli.md
  - Streamlit Dashboard: streamlit.md
  - Roadmap: roadmap.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search
